version: '2'
services:
  wallabag:
    image: gilir/rpi-wallabag
    container_name: wallabag
    restart: always
    volumes:
      - wallabag_data:/var/www/wallabag/data
    external_links:
      - mysql-main:mysql
    ports:
      - "8800:80"
    networks:
      - proxy-network
    labels:
      - "traefik.frontend.rule=Host:wallabag.lavergne.online"
      - "traefik.frontend.passHostHeader=true"

networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  wallabag_data:
    external: true
